<?php

namespace Database\Seeders;

use App\Models\Attribute;
use App\Models\AttributeLink;
use App\Models\AttributeSet;
use App\Models\AttributeValue;
use App\Models\ProductBrand;
use App\Models\ProductCategories;
use App\Models\ProductType;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ProductCategories::upsert([
            ['id' => 1,'name' => 'Weapons', 'parents_id' => null],
            ['id' => 2,'name' => 'Field & Weapon Depot', 'parents_id' => null],
            ['id' => 3,'name' => 'Weapon Parts', 'parents_id' => null],
            ['id' => 4,'name' => 'Mufflers', 'parents_id' => null],
            ['id' => 5,'name' => 'Optics', 'parents_id' => null],
            ['id' => 6,'name' => 'Weapons & Storage', 'parents_id' => null],
            ['id' => 7,'name' => 'Reloading Presses', 'parents_id' => null],
            ['id' => 8,'name' => 'Rifles', 'parents_id' => 1],
            ['id' => 9,'name' => 'Shotguns', 'parents_id' => 1],
            ['id' => 10,'name' => 'Pistol', 'parents_id' => 1],
            ['id' => 11,'name' => 'Buer', 'parents_id' => 1],
            ['id' => 12,'name' => 'Air Weapons', 'parents_id' => 1],
            ['id' => 13,'name' => 'Accessories', 'parents_id' => 2],
            ['id' => 14,'name' => 'Collectors & Antique', 'parents_id' => 1],
            ['id' => 15,'name' => 'Rifles', 'parents_id' => 13],
            ['id' => 16,'name' => 'Shotguns', 'parents_id' => 13],
            ['id' => 17,'name' => 'Pistol', 'parents_id' => 13],
            ['id' => 18,'name' => 'Paintball & Softguns', 'parents_id' => 13],
            ['id' => 19,'name' => 'Clothing Hunters & Competition Shooters', 'parents_id' => 13],
            ['id' => 20,'name' => 'Literature & books', 'parents_id' => 13],
            ['id' => 21,'name' => 'Clay Tablets Throwsers', 'parents_id' => 13],
            ['id' => 22,'name' => 'Shooting targets', 'parents_id' => 13],
            ['id' => 23,'name' => 'Electronic targets', 'parents_id' => 13],
            ['id' => 24,'name' => 'Reloading', 'parents_id' => 13],
            ['id' => 25,'name' => 'Knives', 'parents_id' => 13],
            ['id' => 26,'name' => 'Lock cases', 'parents_id' => 3],
            ['id' => 27,'name' => 'End piece', 'parents_id' => 3],
            ['id' => 28,'name' => 'Gun Stocks', 'parents_id' => 3],
            ['id' => 29,'name' => 'Trigger', 'parents_id' => 3],
            ['id' => 30,'name' => 'Magazine', 'parents_id' => 3],
            ['id' => 31,'name' => 'Pistol', 'parents_id' => 4],
            ['id' => 32,'name' => 'Rifles', 'parents_id' => 4],
            ['id' => 33,'name' => 'Rifle', 'parents_id' => 5],
            ['id' => 34,'name' => 'Pistol', 'parents_id' => 5],
            ['id' => 35,'name' => 'Shotguns', 'parents_id' => 5],
            ['id' => 36,'name' => 'Handheld Binoculars', 'parents_id' => 5],
            ['id' => 37,'name' => 'Air Force', 'parents_id' => 5],
            ['id' => 38,'name' => 'Weapon rack', 'parents_id' => 15],
            ['id' => 39,'name' => 'Slings & Swivels', 'parents_id' => 15],
            ['id' => 40,'name' => 'Bolt balls', 'parents_id' => 15],
            ['id' => 41,'name' => 'Bolts', 'parents_id' => 15],
            ['id' => 42,'name' => 'Ammo boxes', 'parents_id' => 15],
            ['id' => 43,'name' => 'Light & accessories', 'parents_id' => 15],
            ['id' => 44,'name' => 'Lens protectors', 'parents_id' => 15],
            ['id' => 45,'name' => 'Mirageband', 'parents_id' => 15],
            ['id' => 46,'name' => 'Buttstocks', 'parents_id' => 15],
            ['id' => 47,'name' => 'Bore cleaning kits', 'parents_id' => 15],
            ['id' => 48,'name' => 'Shooting slings', 'parents_id' => 15],
            ['id' => 49,'name' => 'Futurals', 'parents_id' => 15],
            ['id' => 50,'name' => 'Bipods Tripods & stocks', 'parents_id' => 15],
            ['id' => 51,'name' => 'Muzzle Brake', 'parents_id' => 15],
            ['id' => 52,'name' => 'Shooting mats', 'parents_id' => 15],
            ['id' => 53,'name' => 'Small parts', 'parents_id' => 15],
            ['id' => 54,'name' => 'Springs', 'parents_id' => 15],
            ['id' => 55,'name' => 'Primers', 'parents_id' => 15],
            ['id' => 56,'name' => 'Slings & Swivels', 'parents_id' => 16],
            ['id' => 57,'name' => 'Grip', 'parents_id' => 16],
            ['id' => 58,'name' => 'Light & accessories', 'parents_id' => 16],
            ['id' => 59,'name' => 'Bore cleaning kits', 'parents_id' => 16],
            ['id' => 60,'name' => 'Bolts', 'parents_id' => 16],
            ['id' => 61,'name' => 'Ammo Boxes & Ammobelts', 'parents_id' => 16],
            ['id' => 62,'name' => 'Weapon rack', 'parents_id' => 16],
            ['id' => 63,'name' => 'Chokes', 'parents_id' => 16],
            ['id' => 64,'name' => 'Small parts', 'parents_id' => 16],
            ['id' => 65,'name' => 'Springs', 'parents_id' => 16],
            ['id' => 66,'name' => 'Primers', 'parents_id' => 16],
            ['id' => 67,'name' => 'Grip', 'parents_id' => 17],
            ['id' => 68,'name' => 'Bore cleaning kits', 'parents_id' => 17],
            ['id' => 69,'name' => 'Cylinders', 'parents_id' => 17],
            ['id' => 70,'name' => 'Speed loaders', 'parents_id' => 17],
            ['id' => 71,'name' => 'Holster Belts Vests', 'parents_id' => 17],
            ['id' => 72,'name' => 'Case & Storage Boxes', 'parents_id' => 17],
            ['id' => 73,'name' => 'Ammo boxes', 'parents_id' => 17],
            ['id' => 74,'name' => 'Small parts', 'parents_id' => 17],
            ['id' => 75,'name' => 'Springs', 'parents_id' => 17],
            ['id' => 76,'name' => 'Primers', 'parents_id' => 17],
            ['id' => 77,'name' => 'Paintball', 'parents_id' => 18],
            ['id' => 78,'name' => 'Soft Gun', 'parents_id' => 18],
            ['id' => 79,'name' => 'Accessories', 'parents_id' => 18],
            ['id' => 80,'name' => 'Clothes', 'parents_id' => 18],
            ['id' => 82,'name' => 'Complete set of clothes Hunter', 'parents_id' => 19],
            ['id' => 83,'name' => 'Shooting jackets', 'parents_id' => 19],
            ['id' => 84,'name' => 'Shooting pants', 'parents_id' => 19],
            ['id' => 85,'name' => 'Shooting shoes', 'parents_id' => 19],
            ['id' => 86,'name' => 'Shooting Gloves', 'parents_id' => 19],
            ['id' => 87,'name' => 'Knee Elbow Protectors', 'parents_id' => 19],
            ['id' => 88,'name' => 'Glasses', 'parents_id' => 19],
            ['id' => 89,'name' => 'Hearing protection', 'parents_id' => 19],
            ['id' => 90,'name' => 'Field shoes-Hunting', 'parents_id' => 19],
            ['id' => 91,'name' => 'Vester Belter Tactical clothing', 'parents_id' => 19],
            ['id' => 92,'name' => 'Hunting clothes', 'parents_id' => 19],
            ['id' => 93,'name' => 'Hunting shoes', 'parents_id' => 19],
            ['id' => 93,'name' => 'Manuals', 'parents_id' => 20],
            ['id' => 94,'name' => 'Reloading books', 'parents_id' => 20],
            ['id' => 95,'name' => 'Magazines', 'parents_id' => 20],
            ['id' => 96,'name' => 'General books', 'parents_id' => 20],
            ['id' => 97,'name' => 'Manual', 'parents_id' => 21],
            ['id' => 98,'name' => 'Electronic', 'parents_id' => 21],
            ['id' => 99,'name' => 'Self-indicators', 'parents_id' => 22],
            ['id' => 100,'name' => 'Steel targets', 'parents_id' => 22],
            ['id' => 101,'name' => 'Paper Targets', 'parents_id' => 22],
            ['id' => 102,'name' => 'Electronic', 'parents_id' => 22],
            ['id' => 103,'name' => 'Parts & Components', 'parents_id' => 22],
            ['id' => 104,'name' => 'Chronographs', 'parents_id' => 23],
            ['id' => 105,'name' => 'Wind Height Barometer meters', 'parents_id' => 23],
            ['id' => 106,'name' => 'GPS & Trackers', 'parents_id' => 23],
            ['id' => 107,'name' => 'Rangefinders', 'parents_id' => 23],
            ['id' => 108,'name' => 'Radio', 'parents_id' => 23],
            ['id' => 109,'name' => 'Shoot cam', 'parents_id' => 23],
            ['id' => 110,'name' => 'Bait Light', 'parents_id' => 23],
            ['id' => 111,'name' => 'Lure Equipment', 'parents_id' => 23],
            ['id' => 112,'name' => 'Tomhylser', 'parents_id' => 24],
            ['id' => 113,'name' => 'Bullets', 'parents_id' => 24],
            ['id' => 114,'name' => 'Gunpowder', 'parents_id' => 24],
            ['id' => 115,'name' => 'Black powder', 'parents_id' => 24],
            ['id' => 116,'name' => 'Firing pin', 'parents_id' => 24],
            ['id' => 117,'name' => 'Spare Parts Reloading presses', 'parents_id' => 24],
            ['id' => 118,'name' => 'Dies & Shell Holders', 'parents_id' => 24],
            ['id' => 120,'name' => 'Scales-Manual-Electronic', 'parents_id' => 24],
            ['id' => 121,'name' => 'Conversion Kit', 'parents_id' => 24],
            ['id' => 122,'name' => 'Sleeve prep & trimmers', 'parents_id' => 24],
            ['id' => 123,'name' => 'Measuring Instruments & Tools', 'parents_id' => 24],
            ['id' => 124,'name' => 'Tumblers & Media', 'parents_id' => 24],
            ['id' => 125,'name' => 'Bullet casting', 'parents_id' => 24],
            ['id' => 126,'name' => 'Gunpowder dispensers', 'parents_id' => 24],
            ['id' => 127,'name' => 'Hunting knives', 'parents_id' => 25],
            ['id' => 128,'name' => 'Custom knives', 'parents_id' => 25],
            //['id' => 129,'name' => 'Swords and others', 'parents_id' => 25],
            ['id' => 130,'name' => 'Gun', 'parents_id' => 112],
            ['id' => 131,'name' => 'Rifle', 'parents_id' => 112],
            ['id' => 134,'name' => 'Wet', 'parents_id' => 124],
            ['id' => 135,'name' => 'Dry', 'parents_id' => 124]
        ], [], ['id']);

        ProductType::upsert([
            ['id' => 1,'name' => 'Drilling', 'product_categories_id' => 8],
            ['id' => 2,'name' => 'Combi', 'product_categories_id' => 8],
            ['id' => 3,'name' => 'Double rifle', 'product_categories_id' => 8],
            ['id' => 4,'name' => 'Semi-automatic', 'product_categories_id' => 8],
            ['id' => 5,'name' => 'Bolt Action', 'product_categories_id' => 8],
            ['id' => 6,'name' => 'Single shot', 'product_categories_id' => 8],
            ['id' => 7,'name' => 'Lever Action', 'product_categories_id' => 8],
            ['id' => 8,'name' => 'Biathlete', 'product_categories_id' => 8],
            ['id' => 9,'name' => 'Salon Rifles-Semi-automatic-Single Shot-Bolt Action', 'product_categories_id' => 8],
            ['id' => 10,'name' => 'Half auto', 'product_categories_id' => 9],
            ['id' => 11,'name' => 'Over Under', 'product_categories_id' => 9],
            ['id' => 12,'name' => 'Side by Side', 'product_categories_id' => 9],
            ['id' => 13,'name' => 'Single shot', 'product_categories_id' => 9],
            ['id' => 14,'name' => 'Skeet-Trap', 'product_categories_id' => 9],
            ['id' => 15,'name' => 'Competition', 'product_categories_id' => 10],
            ['id' => 16,'name' => 'Semiauto', 'product_categories_id' => 10],
            ['id' => 17,'name' => 'Revolver', 'product_categories_id' => 10],
            ['id' => 18,'name' => 'Single shot', 'product_categories_id' => 10],
            ['id' => 19,'name' => 'Concave arches', 'product_categories_id' => 11],
            ['id' => 20,'name' => 'Competition booth', 'product_categories_id' => 11],
            ['id' => 21,'name' => 'Competition', 'product_categories_id' => 12],
            ['id' => 22,'name' => 'Semiauto', 'product_categories_id' => 12],
            ['id' => 23,'name' => 'Revolver', 'product_categories_id' => 12],
            ['id' => 24,'name' => 'Single shot', 'product_categories_id' => 12],
            ['id' => 25,'name' => 'Competition', 'product_categories_id' => 14],
            ['id' => 26,'name' => 'Semiauto', 'product_categories_id' => 14],
            ['id' => 27,'name' => 'Revolver', 'product_categories_id' => 14],
            ['id' => 28,'name' => 'Single shot', 'product_categories_id' => 14],
            ['id' => 29,'name' => '14x1', 'product_categories_id' => 51],
            ['id' => 30,'name' => '14x1.5', 'product_categories_id' => 51],
            ['id' => 31,'name' => '17x1', 'product_categories_id' => 51],
            ['id' => 32,'name' => '5/8¨x24', 'product_categories_id' => 51],
            ['id' => 33,'name' => '17x1', 'product_categories_id' => 51],
            ['id' => 34,'name' => '17x1', 'product_categories_id' => 51],
            ['id' => 35,'name' => '13x1', 'product_categories_id' => 51],
            ['id' => 36,'name' => '15x1', 'product_categories_id' => 51],
            ['id' => 37,'name' => '1/2x20', 'product_categories_id' => 51],
            ['id' => 38,'name' => '1/2x28', 'product_categories_id' => 51],
            ['id' => 39,'name' => 'Beretta', 'product_categories_id' => 63],
            ['id' => 40,'name' => 'Winchester', 'product_categories_id' => 63],
            ['id' => 41,'name' => 'Remington', 'product_categories_id' => 63],
            ['id' => 42,'name' => 'Browning', 'product_categories_id' => 63],
            ['id' => 43,'name' => 'Sauer', 'product_categories_id' => 63],
            ['id' => 44,'name' => 'Other brands', 'product_categories_id' => 63],
            ['id' => 45,'name' => 'Red dot', 'product_categories_id' => 33],
            ['id' => 46,'name' => 'Traditionally', 'product_categories_id' => 33],
            ['id' => 47,'name' => 'Night optics', 'product_categories_id' => 33],
            ['id' => 48,'name' => 'Red dot', 'product_categories_id' => 34],
            ['id' => 49,'name' => 'Traditionally', 'product_categories_id' => 34],
            ['id' => 50,'name' => 'Red dot', 'product_categories_id' => 35],
            ['id' => 51,'name' => 'Traditionally', 'product_categories_id' => 35],
            ['id' => 52,'name' => 'With rangefinder', 'product_categories_id' => 36],
            ['id' => 53,'name' => 'Without rangefinder', 'product_categories_id' => 36],
            ['id' => 54,'name' => 'Traditionally', 'product_categories_id' => 37]
        ], [], ['id']);

        ProductBrand::upsert([
            ['id' => 1,'name' => 'Sako', 'product_categories_id' => 8],
            ['id' => 2,'name' => 'Schults & Larsen', 'product_categories_id' => 8],
            ['id' => 3,'name' => 'Blows', 'product_categories_id' => 8],
            ['id' => 4,'name' => 'Sauer', 'product_categories_id' => 8],
            ['id' => 5,'name' => 'Browning Remington', 'product_categories_id' => 8],
            ['id' => 6,'name' => 'Mauser', 'product_categories_id' => 8],
            ['id' => 7,'name' => 'Howa', 'product_categories_id' => 8],
            ['id' => 8,'name' => 'Weatherby', 'product_categories_id' => 8],
            ['id' => 9,'name' => 'Benelli', 'product_categories_id' => 8],
            ['id' => 10,'name' => 'Ruger', 'product_categories_id' => 8],
            ['id' => 11,'name' => 'Rossler', 'product_categories_id' => 8],
            ['id' => 12,'name' => 'Marlin', 'product_categories_id' => 8],
            ['id' => 13,'name' => 'Barett', 'product_categories_id' => 8],
            ['id' => 14,'name' => 'Christensen Arms', 'product_categories_id' => 8],
            ['id' => 15,'name' => 'Steyr Mannlicher', 'product_categories_id' => 8],
            ['id' => 16,'name' => 'Savage', 'product_categories_id' => 8],
            ['id' => 17,'name' => 'CZ', 'product_categories_id' => 8],
            ['id' => 18,'name' => 'Fabarm', 'product_categories_id' => 8],
            ['id' => 19,'name' => 'Heckler & Koch', 'product_categories_id' => 8],
            ['id' => 20,'name' => 'Hey', 'product_categories_id' => 8],
            ['id' => 21,'name' => 'Kimber', 'product_categories_id' => 8],
            ['id' => 22,'name' => 'Kimber', 'product_categories_id' => 8],
            ['id' => 23,'name' => 'Sabatti', 'product_categories_id' => 8],
            ['id' => 24,'name' => 'Zastava', 'product_categories_id' => 8],
            ['id' => 25,'name' => 'Incense', 'product_categories_id' => 8],
            ['id' => 26,'name' => 'Seekins Precision', 'product_categories_id' => 8],
            ['id' => 27,'name' => 'Protection', 'product_categories_id' => 8],
            ['id' => 28,'name' => 'Winchester', 'product_categories_id' => 9],
            ['id' => 29,'name' => 'Benelli', 'product_categories_id' => 9],
            ['id' => 30,'name' => 'Browning', 'product_categories_id' => 9],
            ['id' => 31,'name' => 'Beretta', 'product_categories_id' => 9],
            ['id' => 32,'name' => 'Franchi', 'product_categories_id' => 9],
            ['id' => 33,'name' => 'Remington', 'product_categories_id' => 9],
            ['id' => 34,'name' => 'Bettinsoli', 'product_categories_id' => 9],
            ['id' => 35,'name' => 'Huglu', 'product_categories_id' => 9],
            ['id' => 36,'name' => 'Darwin', 'product_categories_id' => 9],
            ['id' => 37,'name' => 'Churchill', 'product_categories_id' => 9],
            ['id' => 38,'name' => 'Altay', 'product_categories_id' => 9],
            ['id' => 39,'name' => 'Arrieta', 'product_categories_id' => 9],
            ['id' => 40,'name' => 'FAIR', 'product_categories_id' => 9],
            ['id' => 41,'name' => 'Merkel', 'product_categories_id' => 9],
            ['id' => 42,'name' => 'Fabarm', 'product_categories_id' => 9],
            ['id' => 43,'name' => 'Mossberg', 'product_categories_id' => 9],
            ['id' => 44,'name' => 'Blows', 'product_categories_id' => 9],
            ['id' => 45,'name' => 'Kreighoff', 'product_categories_id' => 9],
            ['id' => 46,'name' => 'Girsan', 'product_categories_id' => 9],
            ['id' => 47,'name' => 'Sabatti', 'product_categories_id' => 9],
            ['id' => 48,'name' => 'Sauer & Shon', 'product_categories_id' => 9],
            ['id' => 49,'name' => 'Pallas', 'product_categories_id' => 9],
            ['id' => 50,'name' => 'Find Classic', 'product_categories_id' => 9],
            ['id' => 51,'name' => 'Classic', 'product_categories_id' => 9],
            ['id' => 52,'name' => 'Baikal', 'product_categories_id' => 9],
            ['id' => 53,'name' => 'ATA Arms', 'product_categories_id' => 9],
            ['id' => 54,'name' => 'Smith & Wesson', 'product_categories_id' => 9],
            ['id' => 55,'name' => 'Beretta', 'product_categories_id' => 10],
            ['id' => 56,'name' => 'Browning', 'product_categories_id' => 10],
            ['id' => 57,'name' => 'Glock', 'product_categories_id' => 10],
            ['id' => 58,'name' => 'Smith & Wesson', 'product_categories_id' => 10],
            ['id' => 59,'name' => 'Ruger', 'product_categories_id' => 10],
            ['id' => 60,'name' => 'BUL', 'product_categories_id' => 10],
            ['id' => 61,'name' => 'Walther', 'product_categories_id' => 10],
            ['id' => 62,'name' => 'Remington', 'product_categories_id' => 10],
            ['id' => 63,'name' => 'Desert Eagle', 'product_categories_id' => 10],
            ['id' => 64,'name' => 'Kimber', 'product_categories_id' => 10],
            ['id' => 65,'name' => 'CZ', 'product_categories_id' => 10],
            ['id' => 66,'name' => 'GSG', 'product_categories_id' => 10],
            ['id' => 67,'name' => 'Hammerli', 'product_categories_id' => 10],
            ['id' => 68,'name' => 'Sig Sauer', 'product_categories_id' => 10],
            ['id' => 69,'name' => 'Springfield Armory', 'product_categories_id' => 10],
            ['id' => 70,'name' => 'Tanfoglio', 'product_categories_id' => 10],
            ['id' => 71,'name' => 'Beretta', 'product_categories_id' => 12],
            ['id' => 72,'name' => 'Browning', 'product_categories_id' => 12],
            ['id' => 73,'name' => 'Glock', 'product_categories_id' => 12],
            ['id' => 74,'name' => 'Smith & Wesson', 'product_categories_id' => 12],
            ['id' => 75,'name' => 'Ruger', 'product_categories_id' => 12],
            ['id' => 76,'name' => 'BUL', 'product_categories_id' => 12],
            ['id' => 77,'name' => 'Walther', 'product_categories_id' => 12],
            ['id' => 78,'name' => 'Remington', 'product_categories_id' => 12],
            ['id' => 79,'name' => 'Desert Eagle', 'product_categories_id' => 12],
            ['id' => 80,'name' => 'Kimber', 'product_categories_id' => 12],
            ['id' => 81,'name' => 'CZ', 'product_categories_id' => 12],
            ['id' => 82,'name' => 'GSG', 'product_categories_id' => 12],
            ['id' => 83,'name' => 'Hammerli', 'product_categories_id' => 12],
            ['id' => 84,'name' => 'Sig Sauer', 'product_categories_id' => 12],
            ['id' => 85,'name' => 'Springfield Armory', 'product_categories_id' => 12],
            ['id' => 86,'name' => 'Tanfoglio', 'product_categories_id' => 12],
            ['id' => 87,'name' => 'Black powder weapons', 'product_categories_id' => 12],
            ['id' => 88,'name' => 'Lapua', 'product_categories_id' => 113],
            ['id' => 89,'name' => 'Berger', 'product_categories_id' => 113],
            ['id' => 90,'name' => 'Barnes', 'product_categories_id' => 113],
            ['id' => 91,'name' => 'Hornady', 'product_categories_id' => 113],
            ['id' => 92,'name' => 'Norma', 'product_categories_id' => 113],
            ['id' => 93,'name' => 'Nosler', 'product_categories_id' => 113],
            ['id' => 94,'name' => 'Sierra', 'product_categories_id' => 113],
            ['id' => 95,'name' => 'Fox Bullets', 'product_categories_id' => 113],
            ['id' => 96,'name' => 'Rhino', 'product_categories_id' => 113],
            ['id' => 97,'name' => 'Geco', 'product_categories_id' => 113],
            ['id' => 98,'name' => 'Swift', 'product_categories_id' => 113],
            ['id' => 99,'name' => 'Federal', 'product_categories_id' => 113],
            ['id' => 100,'name' => 'Woodleigh', 'product_categories_id' => 113],
            ['id' => 101,'name' => 'RWS', 'product_categories_id' => 113],
            ['id' => 102,'name' => 'GGC', 'product_categories_id' => 113],
            ['id' => 103,'name' => 'Partizan', 'product_categories_id' => 113],
            ['id' => 104,'name' => 'S&B', 'product_categories_id' => 113],
            ['id' => 105,'name' => 'Spear', 'product_categories_id' => 113],
            ['id' => 107,'name' => 'Supersonic', 'product_categories_id' => 113],
            ['id' => 108,'name' => 'Norma', 'product_categories_id' => 114],
            ['id' => 109,'name' => 'Vihtavuori', 'product_categories_id' => 114],
            ['id' => 110,'name' => 'Winchester', 'product_categories_id' => 114],
            ['id' => 111,'name' => 'IMR', 'product_categories_id' => 114],
            ['id' => 112,'name' => 'Hodgon', 'product_categories_id' => 114],
            ['id' => 113,'name' => 'Lovex', 'product_categories_id' => 114],
            ['id' => 114,'name' => 'Alliance', 'product_categories_id' => 114],
            ['id' => 115,'name' => 'Vectan', 'product_categories_id' => 114],
            ['id' => 116,'name' => 'Federal', 'product_categories_id' => 116],
            ['id' => 117,'name' => 'RWS', 'product_categories_id' => 116],
            ['id' => 118,'name' => 'Remington', 'product_categories_id' => 116],
            ['id' => 119,'name' => 'CCI', 'product_categories_id' => 116],
            ['id' => 120,'name' => 'Winchester', 'product_categories_id' => 116],
            ['id' => 121,'name' => 'Murom', 'product_categories_id' => 116],
            ['id' => 122,'name' => 'S&B', 'product_categories_id' => 116],
            ['id' => 123,'name' => 'Lyman', 'product_categories_id' => 118],
            ['id' => 124,'name' => 'Lee', 'product_categories_id' => 118],
            ['id' => 125,'name' => 'RCBS', 'product_categories_id' => 118],
            ['id' => 126,'name' => 'Hornady', 'product_categories_id' => 118],
            ['id' => 127,'name' => 'Dillon', 'product_categories_id' => 118],
            ['id' => 128,'name' => 'Forster', 'product_categories_id' => 118],
            ['id' => 129,'name' => 'Rescue', 'product_categories_id' => 118],
            ['id' => 130,'name' => 'Lyman', 'product_categories_id' => 120],
            ['id' => 131,'name' => 'Lee', 'product_categories_id' => 120],
            ['id' => 132,'name' => 'RCBS', 'product_categories_id' => 120],
            ['id' => 133,'name' => 'Hornady', 'product_categories_id' => 120],
            ['id' => 134,'name' => 'Dillon', 'product_categories_id' => 120],
            ['id' => 135,'name' => 'Forster', 'product_categories_id' => 120],
            ['id' => 136,'name' => 'Rescue', 'product_categories_id' => 120],
            ['id' => 137,'name' => 'Lyman', 'product_categories_id' => 122],
            ['id' => 138,'name' => 'Lee', 'product_categories_id' => 122],
            ['id' => 139,'name' => 'RCBS', 'product_categories_id' => 122],
            ['id' => 140,'name' => 'Hornady', 'product_categories_id' => 122],
            ['id' => 141,'name' => 'Dillon', 'product_categories_id' => 122],
            ['id' => 142,'name' => 'Forster', 'product_categories_id' => 122],
            ['id' => 143,'name' => 'Rescue', 'product_categories_id' => 122],
            ['id' => 144,'name' => 'Sako', 'product_categories_id' => 26],
            ['id' => 145,'name' => 'Schults & Larsen', 'product_categories_id' => 26],
            ['id' => 146,'name' => 'Blows', 'product_categories_id' => 26],
            ['id' => 147,'name' => 'Sauer', 'product_categories_id' => 26],
            ['id' => 148,'name' => 'Browning Remington', 'product_categories_id' => 26],
            ['id' => 149,'name' => 'Mauser', 'product_categories_id' => 26],
            ['id' => 150,'name' => 'Howa', 'product_categories_id' => 26],
            ['id' => 151,'name' => 'Weatherby', 'product_categories_id' => 26],
            ['id' => 152,'name' => 'Benelli', 'product_categories_id' => 26],
            ['id' => 153,'name' => 'Ruger', 'product_categories_id' => 26],
            ['id' => 154,'name' => 'Rossler', 'product_categories_id' => 26],
            ['id' => 155,'name' => 'Marlin', 'product_categories_id' => 26],
            ['id' => 156,'name' => 'Barett', 'product_categories_id' => 26],
            ['id' => 157,'name' => 'Christensen Arms', 'product_categories_id' => 26],
            ['id' => 158,'name' => 'Steyr Mannlicher', 'product_categories_id' => 26],
            ['id' => 159,'name' => 'Savage', 'product_categories_id' => 26],
            ['id' => 160,'name' => 'CZ', 'product_categories_id' => 26],
            ['id' => 161,'name' => 'Fabarm', 'product_categories_id' => 26],
            ['id' => 162,'name' => 'Heckler & Koch', 'product_categories_id' => 26],
            ['id' => 163,'name' => 'Hey', 'product_categories_id' => 26],
            ['id' => 164,'name' => 'Kimber', 'product_categories_id' => 26],
            ['id' => 165,'name' => 'Sabatti', 'product_categories_id' => 26],
            ['id' => 166,'name' => 'Zastava', 'product_categories_id' => 26],
            ['id' => 167,'name' => 'Incense', 'product_categories_id' => 26],
            ['id' => 168,'name' => 'Seekins Precision', 'product_categories_id' => 26],
            ['id' => 169,'name' => 'Protection', 'product_categories_id' => 26],
            ['id' => 170,'name' => 'Winchester', 'product_categories_id' => 26],
            ['id' => 171,'name' => 'Beretta', 'product_categories_id' => 26],
            ['id' => 172,'name' => 'Franchi', 'product_categories_id' => 26],
            ['id' => 173,'name' => 'Remington', 'product_categories_id' => 26],
            ['id' => 174,'name' => 'Bettinsoli', 'product_categories_id' => 26],
            ['id' => 175,'name' => 'Huglu', 'product_categories_id' => 26],
            ['id' => 176,'name' => 'Darwin', 'product_categories_id' => 26],
            ['id' => 177,'name' => 'Churchill', 'product_categories_id' => 26],
            ['id' => 178,'name' => 'Altay', 'product_categories_id' => 26],
            ['id' => 179,'name' => 'Arrieta', 'product_categories_id' => 26],
            ['id' => 180,'name' => 'FAIR', 'product_categories_id' => 26],
            ['id' => 181,'name' => 'Merkel', 'product_categories_id' => 26],
            ['id' => 182,'name' => 'Mossberg', 'product_categories_id' => 26],
            ['id' => 183,'name' => 'Kreighoff', 'product_categories_id' => 26],
            ['id' => 184,'name' => 'Girsan', 'product_categories_id' => 26],
            ['id' => 185,'name' => 'Sauer & Shon', 'product_categories_id' => 26],
            ['id' => 186,'name' => 'Pallas', 'product_categories_id' => 26],
            ['id' => 187,'name' => 'Find Classic', 'product_categories_id' => 26],
            ['id' => 188,'name' => 'Classic', 'product_categories_id' => 26],
            ['id' => 189,'name' => 'Baikal', 'product_categories_id' => 26],
            ['id' => 190,'name' => 'ATA Arms', 'product_categories_id' => 26],
            ['id' => 191,'name' => 'Smith & Wesson', 'product_categories_id' => 26],
            ['id' => 192,'name' => 'Beretta', 'product_categories_id' => 26],
            ['id' => 193,'name' => 'Browning', 'product_categories_id' => 26],
            ['id' => 194,'name' => 'Glock', 'product_categories_id' => 26],
            ['id' => 195,'name' => 'Smith & Wesson', 'product_categories_id' => 26],
            ['id' => 196,'name' => 'BUL', 'product_categories_id' => 26],
            ['id' => 197,'name' => 'Walther', 'product_categories_id' => 26],
            ['id' => 198,'name' => 'Remington', 'product_categories_id' => 26],
            ['id' => 199,'name' => 'Desert Eagle', 'product_categories_id' => 26],
            ['id' => 200,'name' => 'CZ', 'product_categories_id' => 26],
            ['id' => 201,'name' => 'GSG', 'product_categories_id' => 26],
            ['id' => 202,'name' => 'Hammerli', 'product_categories_id' => 26],
            ['id' => 203,'name' => 'Sig Sauer', 'product_categories_id' => 26],
            ['id' => 204,'name' => 'Springfield Armory', 'product_categories_id' => 26],
            ['id' => 205,'name' => 'Tanfoglio', 'product_categories_id' => 26],
            ['id' => 206,'name' => 'Sako', 'product_categories_id' => 27],
            ['id' => 207,'name' => 'Schults & Larsen', 'product_categories_id' => 27],
            ['id' => 208,'name' => 'Blows', 'product_categories_id' => 27],
            ['id' => 209,'name' => 'Sauer', 'product_categories_id' => 27],
            ['id' => 210,'name' => 'Browning Remington', 'product_categories_id' => 27],
            ['id' => 211,'name' => 'Mauser', 'product_categories_id' => 27],
            ['id' => 212,'name' => 'Howa', 'product_categories_id' => 27],
            ['id' => 213,'name' => 'Weatherby', 'product_categories_id' => 27],
            ['id' => 214,'name' => 'Benelli', 'product_categories_id' => 27],
            ['id' => 215,'name' => 'Ruger', 'product_categories_id' => 27],
            ['id' => 216,'name' => 'Rossler', 'product_categories_id' => 27],
            ['id' => 217,'name' => 'Marlin', 'product_categories_id' => 27],
            ['id' => 218,'name' => 'Barett', 'product_categories_id' => 27],
            ['id' => 219,'name' => 'Christensen Arms', 'product_categories_id' => 27],
            ['id' => 220,'name' => 'Steyr Mannlicher', 'product_categories_id' => 27],
            ['id' => 221,'name' => 'Savage', 'product_categories_id' => 27],
            ['id' => 222,'name' => 'CZ', 'product_categories_id' => 27],
            ['id' => 223,'name' => 'Fabarm', 'product_categories_id' => 27],
            ['id' => 224,'name' => 'Heckler & Koch', 'product_categories_id' => 27],
            ['id' => 225,'name' => 'Hey', 'product_categories_id' => 27],
            ['id' => 226,'name' => 'Kimber', 'product_categories_id' => 27],
            ['id' => 227,'name' => 'Sabatti', 'product_categories_id' => 27],
            ['id' => 228,'name' => 'Zastava', 'product_categories_id' => 27],
            ['id' => 229,'name' => 'Incense', 'product_categories_id' => 27],
            ['id' => 230,'name' => 'Seekins Precision', 'product_categories_id' => 27],
            ['id' => 231,'name' => 'Protection', 'product_categories_id' => 27],
            ['id' => 232,'name' => 'Winchester', 'product_categories_id' => 27],
            ['id' => 233,'name' => 'Beretta', 'product_categories_id' => 27],
            ['id' => 234,'name' => 'Franchi', 'product_categories_id' => 27],
            ['id' => 235,'name' => 'Remington', 'product_categories_id' => 27],
            ['id' => 236,'name' => 'Bettinsoli', 'product_categories_id' => 27],
            ['id' => 237,'name' => 'Huglu', 'product_categories_id' => 27],
            ['id' => 238,'name' => 'Darwin', 'product_categories_id' => 27],
            ['id' => 239,'name' => 'Churchill', 'product_categories_id' => 27],
            ['id' => 240,'name' => 'Altay', 'product_categories_id' => 27],
            ['id' => 241,'name' => 'Arrieta', 'product_categories_id' => 27],
            ['id' => 242,'name' => 'FAIR', 'product_categories_id' => 27],
            ['id' => 243,'name' => 'Merkel', 'product_categories_id' => 27],
            ['id' => 244,'name' => 'Mossberg', 'product_categories_id' => 27],
            ['id' => 245,'name' => 'Kreighoff', 'product_categories_id' => 27],
            ['id' => 246,'name' => 'Girsan', 'product_categories_id' => 27],
            ['id' => 247,'name' => 'Sauer & Shon', 'product_categories_id' => 27],
            ['id' => 248,'name' => 'Pallas', 'product_categories_id' => 27],
            ['id' => 249,'name' => 'Find Classic', 'product_categories_id' => 27],
            ['id' => 250,'name' => 'Classic', 'product_categories_id' => 27],
            ['id' => 251,'name' => 'Baikal', 'product_categories_id' => 27],
            ['id' => 252,'name' => 'ATA Arms', 'product_categories_id' => 27],
            ['id' => 253,'name' => 'Smith & Wesson', 'product_categories_id' => 27],
            ['id' => 254,'name' => 'Beretta', 'product_categories_id' => 27],
            ['id' => 255,'name' => 'Browning', 'product_categories_id' => 27],
            ['id' => 256,'name' => 'Glock', 'product_categories_id' => 27],
            ['id' => 257,'name' => 'Smith & Wesson', 'product_categories_id' => 27],
            ['id' => 258,'name' => 'BUL', 'product_categories_id' => 27],
            ['id' => 259,'name' => 'Walther', 'product_categories_id' => 27],
            ['id' => 260,'name' => 'Remington', 'product_categories_id' => 27],
            ['id' => 261,'name' => 'Desert Eagle', 'product_categories_id' => 27],
            ['id' => 262,'name' => 'CZ', 'product_categories_id' => 27],
            ['id' => 263,'name' => 'GSG', 'product_categories_id' => 27],
            ['id' => 264,'name' => 'Hammerli', 'product_categories_id' => 27],
            ['id' => 265,'name' => 'Sig Sauer', 'product_categories_id' => 27],
            ['id' => 266,'name' => 'Springfield Armory', 'product_categories_id' => 27],
            ['id' => 267,'name' => 'Tanfoglio', 'product_categories_id' => 27],
            ['id' => 268,'name' => 'KKC', 'product_categories_id' => 28],
            ['id' => 269,'name' => 'GRS', 'product_categories_id' => 28],
            ['id' => 270,'name' => 'Bell & Carlson', 'product_categories_id' => 28],
            ['id' => 271,'name' => 'Boyd', 'product_categories_id' => 28],
            ['id' => 272,'name' => 'HS Precision', 'product_categories_id' => 28],
            ['id' => 273,'name' => 'Tyristubben', 'product_categories_id' => 28],
            ['id' => 274,'name' => 'Holmbro', 'product_categories_id' => 28],
            ['id' => 275,'name' => 'Remington', 'product_categories_id' => 28],
            ['id' => 276,'name' => 'Tikka', 'product_categories_id' => 28],
            ['id' => 277,'name' => 'Sako', 'product_categories_id' => 28],
            ['id' => 278,'name' => 'Schultz & Larsen', 'product_categories_id' => 28],
            ['id' => 279,'name' => 'Browning', 'product_categories_id' => 28],
            ['id' => 280,'name' => 'Custom', 'product_categories_id' => 28],
            ['id' => 281,'name' => 'Other brands', 'product_categories_id' => 28],
            ['id' => 282,'name' => 'Sako', 'product_categories_id' => 29],
            ['id' => 283,'name' => 'Schults & Larsen', 'product_categories_id' => 29],
            ['id' => 284,'name' => 'Blows', 'product_categories_id' => 29],
            ['id' => 285,'name' => 'Sauer', 'product_categories_id' => 29],
            ['id' => 286,'name' => 'Browning Remington', 'product_categories_id' => 29],
            ['id' => 287,'name' => 'Mauser', 'product_categories_id' => 29],
            ['id' => 288,'name' => 'Howa', 'product_categories_id' => 29],
            ['id' => 289,'name' => 'Weatherby', 'product_categories_id' => 29],
            ['id' => 290,'name' => 'Benelli', 'product_categories_id' => 29],
            ['id' => 291,'name' => 'Ruger', 'product_categories_id' => 29],
            ['id' => 292,'name' => 'Rossler', 'product_categories_id' => 29],
            ['id' => 293,'name' => 'Marlin', 'product_categories_id' => 29],
            ['id' => 294,'name' => 'Barett', 'product_categories_id' => 29],
            ['id' => 295,'name' => 'Christensen Arms', 'product_categories_id' => 29],
            ['id' => 296,'name' => 'Steyr Mannlicher', 'product_categories_id' => 29],
            ['id' => 297,'name' => 'Savage', 'product_categories_id' => 29],
            ['id' => 298,'name' => 'CZ', 'product_categories_id' => 29],
            ['id' => 299,'name' => 'Fabarm', 'product_categories_id' => 29],
            ['id' => 300,'name' => 'Heckler & Koch', 'product_categories_id' => 29],
            ['id' => 301,'name' => 'Hey', 'product_categories_id' => 29],
            ['id' => 302,'name' => 'Kimber', 'product_categories_id' => 29],
            ['id' => 303,'name' => 'Sabatti', 'product_categories_id' => 29],
            ['id' => 304,'name' => 'Zastava', 'product_categories_id' => 29],
            ['id' => 305,'name' => 'Incense', 'product_categories_id' => 29],
            ['id' => 306,'name' => 'Seekins Precision', 'product_categories_id' => 29],
            ['id' => 307,'name' => 'Protection', 'product_categories_id' => 29],
            ['id' => 308,'name' => 'Winchester', 'product_categories_id' => 29],
            ['id' => 309,'name' => 'Beretta', 'product_categories_id' => 29],
            ['id' => 310,'name' => 'Franchi', 'product_categories_id' => 29],
            ['id' => 311,'name' => 'Remington', 'product_categories_id' => 29],
            ['id' => 312,'name' => 'Bettinsoli', 'product_categories_id' => 29],
            ['id' => 313,'name' => 'Huglu', 'product_categories_id' => 29],
            ['id' => 314,'name' => 'Darwin', 'product_categories_id' => 29],
            ['id' => 315,'name' => 'Churchill', 'product_categories_id' => 29],
            ['id' => 316,'name' => 'Altay', 'product_categories_id' => 29],
            ['id' => 317,'name' => 'Arrieta', 'product_categories_id' => 29],
            ['id' => 318,'name' => 'FAIR', 'product_categories_id' => 29],
            ['id' => 319,'name' => 'Merkel', 'product_categories_id' => 29],
            ['id' => 320,'name' => 'Mossberg', 'product_categories_id' => 29],
            ['id' => 321,'name' => 'Kreighoff', 'product_categories_id' => 29],
            ['id' => 322,'name' => 'Girsan', 'product_categories_id' => 29],
            ['id' => 323,'name' => 'Sauer & Shon', 'product_categories_id' => 29],
            ['id' => 324,'name' => 'Pallas', 'product_categories_id' => 29],
            ['id' => 325,'name' => 'Find Classic', 'product_categories_id' => 29],
            ['id' => 326,'name' => 'Classic', 'product_categories_id' => 29],
            ['id' => 327,'name' => 'Baikal', 'product_categories_id' => 29],
            ['id' => 328,'name' => 'ATA Arms', 'product_categories_id' => 29],
            ['id' => 329,'name' => 'Smith & Wesson', 'product_categories_id' => 29],
            ['id' => 330,'name' => 'Beretta', 'product_categories_id' => 29],
            ['id' => 331,'name' => 'Browning', 'product_categories_id' => 29],
            ['id' => 332,'name' => 'Glock', 'product_categories_id' => 29],
            ['id' => 333,'name' => 'Smith & Wesson', 'product_categories_id' => 29],
            ['id' => 334,'name' => 'BUL', 'product_categories_id' => 29],
            ['id' => 335,'name' => 'Walther', 'product_categories_id' => 29],
            ['id' => 336,'name' => 'Remington', 'product_categories_id' => 29],
            ['id' => 337,'name' => 'Desert Eagle', 'product_categories_id' => 29],
            ['id' => 338,'name' => 'CZ', 'product_categories_id' => 29],
            ['id' => 339,'name' => 'GSG', 'product_categories_id' => 29],
            ['id' => 340,'name' => 'Hammerli', 'product_categories_id' => 29],
            ['id' => 341,'name' => 'Sig Sauer', 'product_categories_id' => 29],
            ['id' => 342,'name' => 'Springfield Armory', 'product_categories_id' => 29],
            ['id' => 343,'name' => 'Tanfoglio', 'product_categories_id' => 29],
            ['id' => 344,'name' => 'Sako', 'product_categories_id' => 30],
            ['id' => 345,'name' => 'Schults & Larsen', 'product_categories_id' => 30],
            ['id' => 346,'name' => 'Blows', 'product_categories_id' => 30],
            ['id' => 347,'name' => 'Sauer', 'product_categories_id' => 30],
            ['id' => 348,'name' => 'Browning Remington', 'product_categories_id' => 30],
            ['id' => 349,'name' => 'Mauser', 'product_categories_id' => 30],
            ['id' => 350,'name' => 'Howa', 'product_categories_id' => 30],
            ['id' => 351,'name' => 'Weatherby', 'product_categories_id' => 30],
            ['id' => 352,'name' => 'Benelli', 'product_categories_id' => 30],
            ['id' => 353,'name' => 'Ruger', 'product_categories_id' => 30],
            ['id' => 354,'name' => 'Rossler', 'product_categories_id' => 30],
            ['id' => 355,'name' => 'Marlin', 'product_categories_id' => 30],
            ['id' => 356,'name' => 'Barett', 'product_categories_id' => 30],
            ['id' => 357,'name' => 'Christensen Arms', 'product_categories_id' => 30],
            ['id' => 358,'name' => 'Steyr Mannlicher', 'product_categories_id' => 30],
            ['id' => 359,'name' => 'Savage', 'product_categories_id' => 30],
            ['id' => 360,'name' => 'CZ', 'product_categories_id' => 30],
            ['id' => 361,'name' => 'Fabarm', 'product_categories_id' => 30],
            ['id' => 362,'name' => 'Heckler & Koch', 'product_categories_id' => 30],
            ['id' => 363,'name' => 'Hey', 'product_categories_id' => 30],
            ['id' => 364,'name' => 'Kimber', 'product_categories_id' => 30],
            ['id' => 365,'name' => 'Sabatti', 'product_categories_id' => 30],
            ['id' => 366,'name' => 'Zastava', 'product_categories_id' => 30],
            ['id' => 367,'name' => 'Incense', 'product_categories_id' => 30],
            ['id' => 368,'name' => 'Seekins Precision', 'product_categories_id' => 30],
            ['id' => 369,'name' => 'Protection', 'product_categories_id' => 30],
            ['id' => 370,'name' => 'Winchester', 'product_categories_id' => 30],
            ['id' => 371,'name' => 'Beretta', 'product_categories_id' => 30],
            ['id' => 372,'name' => 'Franchi', 'product_categories_id' => 30],
            ['id' => 373,'name' => 'Remington', 'product_categories_id' => 30],
            ['id' => 374,'name' => 'Bettinsoli', 'product_categories_id' => 30],
            ['id' => 375,'name' => 'Huglu', 'product_categories_id' => 30],
            ['id' => 376,'name' => 'Darwin', 'product_categories_id' => 30],
            ['id' => 377,'name' => 'Churchill', 'product_categories_id' => 30],
            ['id' => 378,'name' => 'Altay', 'product_categories_id' => 30],
            ['id' => 379,'name' => 'Arrieta', 'product_categories_id' => 30],
            ['id' => 380,'name' => 'FAIR', 'product_categories_id' => 30],
            ['id' => 381,'name' => 'Merkel', 'product_categories_id' => 30],
            ['id' => 382,'name' => 'Mossberg', 'product_categories_id' => 30],
            ['id' => 383,'name' => 'Kreighoff', 'product_categories_id' => 30],
            ['id' => 384,'name' => 'Girsan', 'product_categories_id' => 30],
            ['id' => 385,'name' => 'Sauer & Shon', 'product_categories_id' => 30],
            ['id' => 386,'name' => 'Pallas', 'product_categories_id' => 30],
            ['id' => 387,'name' => 'Find Classic', 'product_categories_id' => 30],
            ['id' => 388,'name' => 'Classic', 'product_categories_id' => 30],
            ['id' => 389,'name' => 'Baikal', 'product_categories_id' => 30],
            ['id' => 390,'name' => 'ATA Arms', 'product_categories_id' => 30],
            ['id' => 391,'name' => 'Smith & Wesson', 'product_categories_id' => 30],
            ['id' => 392,'name' => 'Beretta', 'product_categories_id' => 30],
            ['id' => 393,'name' => 'Browning', 'product_categories_id' => 30],
            ['id' => 394,'name' => 'Glock', 'product_categories_id' => 30],
            ['id' => 395,'name' => 'Smith & Wesson', 'product_categories_id' => 30],
            ['id' => 396,'name' => 'BUL', 'product_categories_id' => 30],
            ['id' => 397,'name' => 'Walther', 'product_categories_id' => 30],
            ['id' => 398,'name' => 'Remington', 'product_categories_id' => 30],
            ['id' => 399,'name' => 'Desert Eagle', 'product_categories_id' => 30],
            ['id' => 400,'name' => 'CZ', 'product_categories_id' => 30],
            ['id' => 401,'name' => 'GSG', 'product_categories_id' => 30],
            ['id' => 402,'name' => 'Hammerli', 'product_categories_id' => 30],
            ['id' => 403,'name' => 'Sig Sauer', 'product_categories_id' => 30],
            ['id' => 404,'name' => 'Springfield Armory', 'product_categories_id' => 30],
            ['id' => 405,'name' => 'Tanfoglio', 'product_categories_id' => 30],
            ['id' => 406,'name' => 'Beretta', 'product_categories_id' => 31],
            ['id' => 407,'name' => 'Browning', 'product_categories_id' => 31],
            ['id' => 408,'name' => 'Glock', 'product_categories_id' => 31],
            ['id' => 409,'name' => 'Smith & Wesson', 'product_categories_id' => 31],
            ['id' => 410,'name' => 'Ruger', 'product_categories_id' => 31],
            ['id' => 411,'name' => 'BUL', 'product_categories_id' => 31],
            ['id' => 412,'name' => 'Walther', 'product_categories_id' => 31],
            ['id' => 413,'name' => 'Remington', 'product_categories_id' => 31],
            ['id' => 414,'name' => 'Desert Eagle', 'product_categories_id' => 31],
            ['id' => 415,'name' => 'Kimber', 'product_categories_id' => 31],
            ['id' => 416,'name' => 'CZ', 'product_categories_id' => 31],
            ['id' => 417,'name' => 'GSG', 'product_categories_id' => 31],
            ['id' => 418,'name' => 'Hammerli', 'product_categories_id' => 31],
            ['id' => 419,'name' => 'Sig Sauer', 'product_categories_id' => 31],
            ['id' => 420,'name' => 'Springfield Armory', 'product_categories_id' => 31],
            ['id' => 421,'name' => 'Tanfoglio', 'product_categories_id' => 31],
            ['id' => 422,'name' => 'Sako', 'product_categories_id' => 32],
            ['id' => 423,'name' => 'Schults & Larsen', 'product_categories_id' => 32],
            ['id' => 424,'name' => 'Blows', 'product_categories_id' => 32],
            ['id' => 425,'name' => 'Sauer', 'product_categories_id' => 32],
            ['id' => 426,'name' => 'Browning Remington', 'product_categories_id' => 32],
            ['id' => 427,'name' => 'Mauser', 'product_categories_id' => 32],
            ['id' => 428,'name' => 'Howa', 'product_categories_id' => 32],
            ['id' => 429,'name' => 'Weatherby', 'product_categories_id' => 32],
            ['id' => 430,'name' => 'Benelli', 'product_categories_id' => 32],
            ['id' => 431,'name' => 'Ruger', 'product_categories_id' => 32],
            ['id' => 432,'name' => 'Rossler', 'product_categories_id' => 32],
            ['id' => 433,'name' => 'Marlin', 'product_categories_id' => 32],
            ['id' => 434,'name' => 'Barett', 'product_categories_id' => 32],
            ['id' => 435,'name' => 'Christensen Arms', 'product_categories_id' => 32],
            ['id' => 436,'name' => 'Steyr Mannlicher', 'product_categories_id' => 32],
            ['id' => 437,'name' => 'Savage', 'product_categories_id' => 32],
            ['id' => 438,'name' => 'CZ', 'product_categories_id' => 32],
            ['id' => 439,'name' => 'Fabarm', 'product_categories_id' => 32],
            ['id' => 440,'name' => 'Heckler & Koch', 'product_categories_id' => 32],
            ['id' => 441,'name' => 'Hey', 'product_categories_id' => 32],
            ['id' => 442,'name' => 'Kimber', 'product_categories_id' => 32],
            ['id' => 443,'name' => 'Kimber', 'product_categories_id' => 32],
            ['id' => 444,'name' => 'Sabatti', 'product_categories_id' => 32],
            ['id' => 445,'name' => 'Zastava', 'product_categories_id' => 32],
            ['id' => 446,'name' => 'Incense', 'product_categories_id' => 32],
            ['id' => 447,'name' => 'Seekins Precision', 'product_categories_id' => 32],
            ['id' => 448,'name' => 'Protection', 'product_categories_id' => 32],
            ['id' => 449,'name' => 'Lyman', 'product_categories_id' => 7],
            ['id' => 450,'name' => 'Lee', 'product_categories_id' => 7],
            ['id' => 451,'name' => 'RCBS', 'product_categories_id' => 7],
            ['id' => 452,'name' => 'Hornady', 'product_categories_id' => 7],
            ['id' => 453,'name' => 'Dillon', 'product_categories_id' => 7],
            ['id' => 454,'name' => 'Forster', 'product_categories_id' => 7],
            ['id' => 455,'name' => 'Rescue', 'product_categories_id' => 7]
        ], [], ['id']);

        AttributeSet::upsert([
            ['id' => 1, 'name' => 'Caliber']
        ], [], ['id']);

        Attribute::upsert([
            ['id' => 1, 'name' => 'Rifles', 'is_filterable' => 1, 'attribute_sets_id' => 1],
            ['id' => 2, 'name' => 'Shotguns', 'is_filterable' => 1, 'attribute_sets_id' => 1],
            ['id' => 3, 'name' => 'Pistol', 'is_filterable' => 1, 'attribute_sets_id' => 1]
        ], [], ['id']);

        AttributeValue::upsert([
            ['id' => 2, 'name' => '6.5x55', 'attributes_id' => 1],
            ['id' => 3, 'name' => '6.5 Creedmoor', 'attributes_id' => 1],
            ['id' => 4, 'name' => '308 Winchester', 'attributes_id' => 1],
            ['id' => 5, 'name' => '30.06 Springfield', 'attributes_id' => 1],
            ['id' => 6, 'name' => '22-250 Remington', 'attributes_id' => 1],
            ['id' => 7, 'name' => '223 Remington', 'attributes_id' => 1],
            ['id' => 8, 'name' => '22 Hornet', 'attributes_id' => 1],
            ['id' => 9, 'name' => '17 HMR', 'attributes_id' => 1],
            ['id' => 10, 'name' => '22LR', 'attributes_id' => 1],
            ['id' => 11, 'name' => '221 Remington Fireball', 'attributes_id' => 1],
            ['id' => 12, 'name' => '222 Remington', 'attributes_id' => 1],
            ['id' => 13, 'name' => '243 Winchester', 'attributes_id' => 1],
            ['id' => 14, 'name' => '6mm XC', 'attributes_id' => 1],
            ['id' => 15, 'name' => '6.5x47 Lapua', 'attributes_id' => 1],
            ['id' => 16, 'name' => '260 Remington', 'attributes_id' => 1],
            ['id' => 17, 'name' => '6.5-284 Norma', 'attributes_id' => 1],
            ['id' => 18, 'name' => '270 Winchester', 'attributes_id' => 1],
            ['id' => 19, 'name' => '284 Winchester', 'attributes_id' => 1],
            ['id' => 20, 'name' => '300 H&H', 'attributes_id' => 1],
            ['id' => 21, 'name' => '300 Black Out', 'attributes_id' => 1],
            ['id' => 22, 'name' => '300 Winchester Magnum', 'attributes_id' => 1],
            ['id' => 23, 'name' => '300 Norma Magnum', 'attributes_id' => 1],
            ['id' => 24, 'name' => '300 Blaser Magnum', 'attributes_id' => 1],
            ['id' => 25, 'name' => '300 Lapua Magnum', 'attributes_id' => 1],
            ['id' => 26, 'name' => '338 Lapua Magnum', 'attributes_id' => 1],
            ['id' => 27, 'name' => '338 Winchester Magnum', 'attributes_id' => 1],
            ['id' => 28, 'name' => '338 RUM', 'attributes_id' => 1],
            ['id' => 29, 'name' => '6.5 - 284 Norma', 'attributes_id' => 1],
            ['id' => 30, 'name' => '6.5 Creedmoor', 'attributes_id' => 1],
            ['id' => 31, 'name' => '7mm-08', 'attributes_id' => 1],
            ['id' => 32, 'name' => '7x57', 'attributes_id' => 1],
            ['id' => 33, 'name' => '7x57R', 'attributes_id' => 1],
            ['id' => 34, 'name' => '7x64', 'attributes_id' => 1],
            ['id' => 35, 'name' => '7mm Remington Magnum', 'attributes_id' => 1],
            ['id' => 36, 'name' => '7mm-08 Remington', 'attributes_id' => 1],
            ['id' => 37, 'name' => '7mm WSM', 'attributes_id' => 1],
            ['id' => 38, 'name' => '9.3x62', 'attributes_id' => 1],
            ['id' => 39, 'name' => '9.3x 74R', 'attributes_id' => 1],
            ['id' => 40, 'name' => '9.3x66 SAKO', 'attributes_id' => 1],
            ['id' => 41, 'name' => '8x68 S', 'attributes_id' => 1],
            ['id' => 42, 'name' => '8x57 IRS', 'attributes_id' => 1],
            ['id' => 43, 'name' => '8x58IS Mauser', 'attributes_id' => 1],
            ['id' => 44, 'name' => '375 H&H', 'attributes_id' => 1],
            ['id' => 45, 'name' => '416 Rigby', 'attributes_id' => 1],
            ['id' => 46, 'name' => '444 Marlin', 'attributes_id' => 1],
            ['id' => 47, 'name' => '458 Lott', 'attributes_id' => 1],
            ['id' => 48, 'name' => '458 Winchester Magnum', 'attributes_id' => 1],
            ['id' => 49, 'name' => '470 NE', 'attributes_id' => 1],
            ['id' => 50, 'name' => '500 NE', 'attributes_id' => 1],
            ['id' => 51, 'name' => '45-70 Government', 'attributes_id' => 1],
            ['id' => 52, 'name' => '30.30 Winchester', 'attributes_id' => 1],
            ['id' => 53, 'name' => '30- 378 Weather by Magnum', 'attributes_id' => 1],
            ['id' => 54, 'name' => '50 Browning', 'attributes_id' => 1],
            ['id' => 55, 'name' => 'Kal 12', 'attributes_id' => 2],
            ['id' => 56, 'name' => 'Kal 16', 'attributes_id' => 2],
            ['id' => 57, 'name' => 'Kal 20', 'attributes_id' => 2],
            ['id' => 58, 'name' => 'Kal 10', 'attributes_id' => 2],
            ['id' => 59, 'name' => '357 Magnum', 'attributes_id' => 3],
            ['id' => 60, 'name' => '44 Magnum', 'attributes_id' => 3],
            ['id' => 61, 'name' => '454', 'attributes_id' => 3],
            ['id' => 62, 'name' => '22LR', 'attributes_id' => 3],
            ['id' => 63, 'name' => '9mm', 'attributes_id' => 3],
            ['id' => 64, 'name' => '45 ACP', 'attributes_id' => 3],
            ['id' => 65, 'name' => '45 Auto', 'attributes_id' => 3],
            ['id' => 66, 'name' => '38 Special', 'attributes_id' => 3],
            ['id' => 67, 'name' => '32 ACP', 'attributes_id' => 3],
            ['id' => 68, 'name' => '50 S&W', 'attributes_id' => 3],
            ['id' => 69, 'name' => '50AE', 'attributes_id' => 3],
            ['id' => 70, 'name' => '3 shots', 'attributes_id' => 1],
            ['id' => 71, 'name' => '5 shots', 'attributes_id' => 1],
            ['id' => 72, 'name' => '10 shots', 'attributes_id' => 1],
            ['id' => 73, 'name' => '3 shots', 'attributes_id' => 2],
            ['id' => 74, 'name' => '5 shots', 'attributes_id' => 2],
            ['id' => 75, 'name' => '10 shots', 'attributes_id' => 2],
            ['id' => 76, 'name' => '3 shots', 'attributes_id' => 3],
            ['id' => 77, 'name' => '5 shots', 'attributes_id' => 3],
            ['id' => 78, 'name' => '10 shots', 'attributes_id' => 3]
        ], [], ['id']);


        AttributeLink::upsert([
            ['id' => 1, 'product_categories_id' => 8,  'attributes_id' => 1],
            ['id' => 2, 'product_categories_id' => 9,  'attributes_id' => 2],
            ['id' => 3, 'product_categories_id' => 10,  'attributes_id' => 3]
        ], [], ['id']);


    }
}
